### PR TITLE
Conversion of part 1 to metanorma asciidoc

### PR DESCRIPTION
**Pull request by ghobona**
This pull request contains changes that convert OGC API - Common - Part 1 to metanorma asciidoc.

### CODE REVIEW

**Comment by cmheazel** [comment]
This branch still needs some work:
1) The Scope and Conformance sections are swapped in the PDF rendering
2) The table of contents of the Word rendering includes the copyright notice and license agreement
3) Twelve "Hanging paragraph in clause" errors reported by Metanorma
4) Five XML syntax errors reported by Metanorma
I have fixed a number of other errors, but I will need some help on these four.

Note: I am also moving POI and API-Coverages to Metanorma. I'm having similar issues with these repositories.

**Comment by cmheazel** [comment]
Question - Other repositories use the document number to identify the directory where the asciidoc files reside and also as the file name of the generated documentation. Should we convert API-Common to follow this pattern? (I vote yes).

**Comment by ghobona** [comment]
@cmheazel We generally ignore the "Hanging paragraph in clause" error messages because they do not affect the HTML and PDF rendering. Similarly with the Metanorma XML Syntax, they relate to the metanorma XML document - which we do not publish.

**Comment by ghobona** [comment]
@cmheazel Thanks for spotting the swapped sections. I have just raised a ticket (https://github.com/metanorma/metanorma-ogc/issues/403) for the attention of @ronaldtse.

**Comment by cmheazel** [comment]
Question - should requirements and recommendations in the text be numbered or identified by their URI.
ex: Requirement 1 vs. Requirement /req/core/http

**Comment by ghobona** [comment]
Requirements and other specification elements should be identified by URI (e.g. /req/core/http).

However, to make it easier to read the document, we let metanorma automatically number the Requirements.

References from other specification elements to Requirements should use the URIs of the referenced Requirements.

**Comment by ghobona** [comment]
@cmheazel Please only review the HTML and PDF documents. OGC only publishes HTML and PDF documents.

**Pull request merged**
